import { 
  Wallet, 
  Circle, 
  Hexagon, 
  Square,
  Zap,
  Shield,
  Lock,
  Key,
  Coins,
  CreditCard,
  Smartphone,
  HardDrive,
  Server,
  Globe,
  Layers,
  Box,
  Package,
  Network,
  Activity,
  Sparkles,
  Star,
  Gem,
  Crown,
  Rocket,
  Flame,
  Droplet,
  Sun,
  Moon,
  Cloud,
  Gamepad,
  Waves,
  type LucideIcon
} from 'lucide-vue-next'

export const useWalletIcons = () => {
  const iconMap: Record<string, LucideIcon> = {
    // Popular wallets - using distinct icons
    'metamask': Hexagon,
    'phantom': Circle,
    'trust': Shield,
    'walletconnect': Network,
    'coinbase': Coins,
    'ledger': HardDrive,
    'trezor': Shield,
    'okx': Zap,
    'uniswap': Layers,
    'rabby': Wallet,
    
    // Hardware wallets
    'keystone': Shield,
    'lattice1': Server,
    'gridplus-lattice': Server,
    'gridplus': Server,
    'secux': Smartphone,
    'satochip': CreditCard,
    'coolwallet': CreditCard,
    'ellipal': Smartphone,
    'bitbox': Box,
    'keepkey': Key,
    'coldcard': Lock,
    'passport': Shield,
    'jade': Gem,
    
    // Exchange wallets
    'binance': Coins,
    'kucoin': Coins,
    'okx': Zap,
    'gate': Coins,
    'bitget': Coins,
    'kraken': Coins,
    'coinbase': Coins,
    'coindcx': Coins,
    'coinhako': Coins,
    'coincheck': Coins,
    'bitstamp': Coins,
    'wazirx': Coins,
    'indodax': Coins,
    'zebpay': Coins,
    'huobi': Coins,
    
    // Software wallets
    'exodus': Flame,
    'atomic': Activity,
    'trust': Shield,
    'coinomi': Circle,
    'guarda': Shield,
    'edge': Hexagon,
    'blue': Droplet,
    'electrum': Zap,
    'phoenix': Flame,
    'samourai': Crown,
    'wasabi': Circle,
    'sparrow': Activity,
    'specter': Shield,
    'muun': Moon,
    'breez': Cloud,
    'blixt': Zap,
    'wallet-of-satoshi': Sun,
    
    // Browser extension wallets
    'metamask': Hexagon,
    'phantom': Circle,
    'rabby': Wallet,
    'frame': Square,
    'brave': Shield,
    'opera': Globe,
    'tokenary': Key,
    
    // Mobile wallets
    'trust': Shield,
    'coinbase': Coins,
    'atomic': Activity,
    'exodus': Flame,
    'coinomi': Circle,
    'guarda': Shield,
    'edge': Hexagon,
    'crypto.com': Coins,
    'bitpay': CreditCard,
    'blue': Droplet,
    
    // DeFi/Web3 wallets
    'uniswap': Layers,
    'zerion': Network,
    'rainbow': Sparkles,
    'argent': Shield,
    'gnosis': Shield,
    'safe': Shield,
    'sequence': Layers,
    'authereum': Key,
    'portis': Box,
    'fortmatic': Shield,
    'torus': Circle,
    'magic': Sparkles,
    
    // Chain-specific wallets
    'polkadot': Network,
    'polkawallet': Network,
    'subwallet': Network,
    'talisman': Shield,
    'keplr': Star,
    'cosmostation': Globe,
    'leap': Rocket,
    'juno': Activity,
    'near': Circle,
    'sender': Key,
    'here': Globe,
    'myalgo': Key,
    'pera': Circle,
    'algorand': Circle,
    'algosigner': Key,
    'nami': Hexagon,
    'eternl': Star,
    'flint': Flame,
    'lace': Gem,
    'yoroi': Shield,
    'daedalus': Crown,
    'tonkeeper': Coins,
    'tonhub': Globe,
    'ton': Coins,
    'tronlink': Network,
    'tronwallet': Network,
    'vechain': Network,
    'hedera': Network,
    'icon': Circle,
    'iconex': Network,
    'flow': Droplet,
    'immutable': Shield,
    'starknet': Hexagon,
    'argent-x': Shield,
    'braavos': Shield,
    'zkSync': Layers,
    'linea': Network,
    'scroll': Layers,
    
    // Specialized wallets
    'gamestop': Gamepad,
    'xportal': Smartphone,
    'enjin': Gem,
    'dapper': Crown,
    'valora': Circle,
    'celo': Circle,
    'theta': Circle,
    'waves-exchange': Waves,
    'waves-keeper': Waves,
    'steem': Key,
    'star-atlas': Star,
    'sollet': Sun,
    'solflare': Sun,
    'slope': Layers,
    'phantom': Circle,
    'backpack': Package,
    'glow': Sparkles,
    'math': Box,
    'tokenpocket': Wallet,
    'imtoken': Circle,
    'bitkeep': Wallet,
    'safepal': Shield,
    'klever': Key,
    'ronin': Shield,
    'wombat': Circle,
    'onekey': Key,
    'begin': Rocket,
    'horizon': Sun,
    'cake': Circle,
    'cosmostation': Globe,
    'airgap': Shield,
    'fully-noded': Server,
    'mynode': Server,
    'umbrel': Cloud,
    'casa': Shield,
    'casa-multisig': Shield,
    'caravan': Shield,
    'caravan-multisig': Shield,
    'specter': Shield,
    'sparrow': Activity,
    'wasabi': Circle,
    'electrum': Zap,
    'electrum-ltc': Zap,
    'blue': Droplet,
    'phoenix': Flame,
    'breez': Cloud,
    'blixt': Zap,
    'wallet-of-satoshi': Sun,
    'zeus': Zap,
    'zap': Zap,
    'eclair': Zap,
    'lndmobile': Smartphone,
    'breeze': Cloud,
    'river': Droplet,
    'strike': Zap,
    'opendime': Key,
    'ngrave': Shield,
    'jade': Gem,
    'passport': Shield,
    'coldcard': Lock,
    'tangem': CreditCard,
    'zengo': Shield,
    'magic': Sparkles,
    'torus': Circle,
    'brave': Shield,
    'status': Circle,
    'imtoken': Circle,
    'tokenpocket': Wallet,
    'xdefi': Network,
    'daedalus': Crown,
    'yoroi': Shield,
    'talisman': Shield,
    'subwallet': Network,
    'keplr': Star,
    'scroll': Layers,
    'linea': Network,
    'zksync': Layers,
    'braavos': Shield,
    'argent-x': Shield,
    'fireblocks': Shield,
    'casa': Shield,
    'specter': Shield,
    'sparrow': Activity,
    'wasabi': Circle,
    'muun': Moon,
    'kraken-self-custody': Coins,
    'bybit': Coins,
    'crypto.com': Coins,
    'ledger-live': HardDrive,
    'mycrypto': Wallet,
    'myetherwallet': Wallet,
    'argent': Shield,
    'gnosis-safe': Shield,
    'xaman': Smartphone,
    'binance': Coins,
    'nuls': Network,
    'wax': Circle,
    'wombat': Circle,
    'bitgo': Shield,
    'protonchain': Network,
    'energyweb': Network,
    'chiliz': Coins,
    'loopring': Circle,
    '1inch': Layers,
    'debank': Network,
    'gala': Star,
    'wemix': Network,
    'zebpay': Coins,
    'huobi': Coins,
    'feather': Activity,
    'coinomi': Circle,
    'guarda': Shield,
    'keepkey': Key,
    'bitbox': Box,
    'coolwallet': CreditCard,
    'ellipal': Smartphone,
    'coin98': Circle,
    'bitpie': Wallet,
    'edge': Hexagon,
    'steemkeychain': Key,
    'shimmer': Sparkles,
    'sepior': Shield,
    'greenaddress': Shield,
  }
  
  // Fallback icons for different wallet categories
  const categoryIcons: Record<string, LucideIcon> = {
    'hardware': HardDrive,
    'mobile': Smartphone,
    'desktop': Box,
    'browser': Globe,
    'defi': Layers,
    'exchange': Coins,
    'default': Wallet,
  }
  
  const getWalletIcon = (walletId: string): LucideIcon => {
    return iconMap[walletId.toLowerCase()] || categoryIcons.default
  }
  
  return {
    getWalletIcon,
    iconMap,
  }
}

