export interface Wallet {
  id: string
  name: string
  icon?: string
  isPopular?: boolean
}

export const useWallets = () => {
  const wallets: Wallet[] = [
    // Popular wallets
    { id: 'metamask', name: 'MetaMask', isPopular: true },
    { id: 'phantom', name: 'Phantom Wallet', isPopular: true },
    { id: 'trust', name: 'Trust Wallet', isPopular: true },
    { id: 'walletconnect', name: 'Wallet Connect', isPopular: true },
    { id: 'coinbase', name: 'Coinbase Wallet', isPopular: true },
    { id: 'ledger', name: 'Ledger', isPopular: true },
    { id: 'trezor', name: 'Trezor Wallet', isPopular: true },
    { id: 'okx', name: 'OKX Wallet', isPopular: true },
    { id: 'uniswap', name: 'Uniswap Wallet', isPopular: true },
    { id: 'rabby', name: 'Rabby Wallet', isPopular: true },
    
    // Other wallets
    { id: 'exodus', name: 'Exodus Wallet' },
    { id: 'zerion', name: 'Zerion Wallet' },
    { id: 'bitget', name: 'Bitget Wallet' },
    { id: 'atomic', name: 'Atomic Wallet' },
    { id: 'cosmostation', name: 'Cosmostation Wallet' },
    { id: 'cake', name: 'Cake Wallet' },
    { id: 'horizon', name: 'Horizon Wallet' },
    { id: 'tonkeeper', name: 'Tonkeeper' },
    { id: 'safepal', name: 'SafePal Wallet' },
    { id: 'klever', name: 'Klever Wallet' },
    { id: 'leap', name: 'Leap Wallet' },
    { id: 'ronin', name: 'Ronin Wallet' },
    { id: 'math', name: 'MathWallet' },
    { id: 'begin', name: 'Begin Wallet' },
    { id: 'gate', name: 'Gate.io Wallet' },
    { id: 'onekey', name: 'OneKey Wallet' },
    { id: 'kucoin', name: 'KuCoin Wallet' },
    { id: 'electrum', name: 'Electrum Wallet' },
    { id: 'blue', name: 'Blue Wallet' },
    { id: 'kraken', name: 'Kraken Wallet' },
    { id: 'phoenix', name: 'Phoenix Wallet' },
    { id: 'bitpay', name: 'BitPay Wallet' },
    { id: 'bit2me', name: 'Bit2Me Wallet' },
    { id: 'bitso', name: 'Bitso Wallet' },
    { id: 'flow', name: 'Flow Wallet' },
    { id: 'armory', name: 'Armory Wallet' },
    { id: 'zilpay', name: 'ZilPay' },
    { id: 'zeus', name: 'Zeus' },
    { id: 'zap', name: 'Zap' },
    { id: 'xportal', name: 'xPortal' },
    { id: 'wazirx', name: 'WazirX' },
    { id: 'waves-exchange', name: 'Waves.Exchange' },
    { id: 'waves-keeper', name: 'Waves Keeper' },
    { id: 'wallet-of-satoshi', name: 'Wallet of Satoshi' },
    { id: 'venly', name: 'Venly' },
    { id: 'vechain', name: 'VeChainThor' },
    { id: 'valora', name: 'Valora' },
    { id: 'unstoppable', name: 'Unstoppable' },
    { id: 'umbrel', name: 'Umbrel Wallet' },
    { id: 'typhon', name: 'Typhon' },
    { id: 'tronwallet', name: 'TronWallet' },
    { id: 'tronlink', name: 'TronLink' },
    { id: 'tonhub', name: 'Tonhub' },
    { id: 'tokenary', name: 'Tokenary' },
    { id: 'theta', name: 'Theta Wallet' },
    { id: 'strike', name: 'Strike' },
    { id: 'steem', name: 'Steem Keychain / Hive Keychain' },
    { id: 'star-atlas', name: 'Star Atlas Wallet' },
    { id: 'sollet', name: 'Sollet' },
    { id: 'solflare', name: 'Solflare' },
    { id: 'slope', name: 'Slope' },
    { id: 'sequence', name: 'Sequence' },
    { id: 'sender', name: 'Sender' },
    { id: 'secux', name: 'SecuX' },
    { id: 'satochip', name: 'Satochip' },
    { id: 'samourai', name: 'Samourai' },
    { id: 'river', name: 'River / River Wallet' },
    { id: 'ripio', name: 'Ripio' },
    { id: 'portis', name: 'Portis' },
    { id: 'polkawallet', name: 'Polkawallet' },
    { id: 'polkadot', name: 'Polkadot.js' },
    { id: 'pirate', name: 'Pirate Chain wallet' },
    { id: 'pillar', name: 'Pillar' },
    { id: 'pera', name: 'Pera Wallet' },
    { id: 'opera', name: 'Opera Crypto' },
    { id: 'nova', name: 'Nova' },
    { id: 'nimiq', name: 'Nimiq Wallet' },
    { id: 'near', name: 'Near Wallet' },
    { id: 'nami', name: 'Nami' },
    { id: 'mynode', name: 'MyNode Wallet' },
    { id: 'myalgo', name: 'MyAlgo' },
    { id: 'moonlet', name: 'Moonlet' },
    { id: 'meteor', name: 'Meteor' },
    { id: 'lndmobile', name: 'LNDmobile' },
    { id: 'lattice1', name: 'Lattice1' },
    { id: 'lace', name: 'Lace' },
    { id: 'keystone', name: 'Keystone' },
    { id: 'juno', name: 'Juno/Kujira/Evmos' },
    { id: 'jaxx', name: 'Jaxx Liberty' },
    { id: 'indodax', name: 'Indodax' },
    { id: 'immutable', name: 'ImmutableX wallet' },
    { id: 'iconex', name: 'ICONex' },
    { id: 'icon', name: 'ICON wallet' },
    { id: 'here', name: 'Here Wallet' },
    { id: 'hedera', name: 'Hedera Hashgraph HashPack' },
    { id: 'gridplus-lattice', name: 'GridPlus Lattice' },
    { id: 'gridplus', name: 'GridPlus' },
    { id: 'gordian', name: 'Gordian' },
    { id: 'glow', name: 'Glow' },
    { id: 'gemini', name: 'Gemini Self-Custody' },
    { id: 'gamestop', name: 'GameStop Wallet' },
    { id: 'fully-noded', name: 'Fully Noded' },
    { id: 'frame', name: 'Frame' },
    { id: 'flint', name: 'Flint' },
    { id: 'eternl', name: 'Eternl' },
    { id: 'eos', name: 'EOS Anchor' },
    { id: 'enjin', name: 'Enjin Wallet' },
    { id: 'elrond', name: 'Elrond / MultiversX Maiar' },
    { id: 'eclair', name: 'Eclair' },
    { id: 'dapper', name: 'Dapper' },
    { id: 'curv', name: 'Curv' },
    { id: 'cryptotag', name: 'Cryptotag' },
    { id: 'copper', name: 'Copper Custody' },
    { id: 'coinstats', name: 'CoinStats Wallet' },
    { id: 'coinhako', name: 'Coinhako' },
    { id: 'coindcx', name: 'CoinDCX' },
    { id: 'coincheck', name: 'Coincheck' },
    { id: 'coin-space', name: 'Coin.Space' },
    { id: 'celo', name: 'Celo Valora' },
    { id: 'caravan', name: 'Caravan multisig' },
    { id: 'breeze', name: 'Breeze' },
    { id: 'breez', name: 'Breez' },
    { id: 'brd', name: 'BRD / Bread' },
    { id: 'blocto', name: 'Blocto' },
    { id: 'blixt', name: 'Blixt' },
    { id: 'blade', name: 'Blade Wallet' },
    { id: 'bitstamp', name: 'Bitstamp / regional exchange wallet' },
    { id: 'bitlox', name: 'BitLox' },
    { id: 'bitkeep', name: 'BitKeep' },
    { id: 'bitfi', name: 'Bitfi' },
    { id: 'billfodl', name: 'Billfodl / Cryptosteel' },
    { id: 'ballet', name: 'Ballet' },
    { id: 'backpack', name: 'Backpack' },
    { id: 'authereum', name: 'Authereum' },
    { id: 'aurora', name: 'Aurora Wallet' },
    { id: 'arkane', name: 'Arkane' },
    { id: 'anchorage', name: 'Anchorage' },
    { id: 'algosigner', name: 'AlgoSigner' },
    { id: 'algorand', name: 'Algorand official' },
    { id: 'alby', name: 'Alby' },
    { id: 'airgap', name: 'AirGap' },
  ]

  const getPopularWallets = () => wallets.filter(w => w.isPopular)
  const getAllWallets = () => wallets
  const searchWallets = (query: string) => {
    if (!query) return wallets
    const lowerQuery = query.toLowerCase()
    return wallets.filter(w => w.name.toLowerCase().includes(lowerQuery))
  }

  return {
    wallets,
    getPopularWallets,
    getAllWallets,
    searchWallets,
  }
}

